# Generated by Django 5.2.4 on 2025-07-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hyderabad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                (
                    "job_titles",
                    models.CharField(
                        choices=[
                            ("engineer", "engineer"),
                            ("manager", "manager"),
                            ("admin", "admin"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sal", models.IntegerField()),
                (
                    "qualifications",
                    models.CharField(
                        choices=[("cse", "cse"), ("btech", "btech"), ("me", "me")],
                        max_length=100,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Mumbai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                (
                    "job_titles",
                    models.CharField(
                        choices=[
                            ("engineer", "engineer"),
                            ("manager", "manager"),
                            ("admin", "admin"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sal", models.IntegerField()),
                (
                    "qualifications",
                    models.CharField(
                        choices=[("cse", "cse"), ("btech", "btech"), ("me", "me")],
                        max_length=100,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                (
                    "job_titles",
                    models.CharField(
                        choices=[
                            ("engineer", "engineer"),
                            ("manager", "manager"),
                            ("admin", "admin"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sal", models.IntegerField()),
                (
                    "qualifications",
                    models.CharField(
                        choices=[("cse", "cse"), ("btech", "btech"), ("me", "me")],
                        max_length=100,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
    ]
